-- 코드를 입력하세요
SELECT A.AUTHOR_ID as AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, sum(PRICE * SALES) as TOTAL_SALES
FROM BOOK as B inner join AUTHOR as A on B.AUTHOR_ID = A.AUTHOR_ID
 inner join 
(SELECT BOOK_ID, sum(SALES) as SALES
FROM BOOK_SALES
WHERE SALES_DATE like "2022-01%"
group by BOOK_ID) as BS on B.BOOK_ID = BS.BOOK_ID
group by CATEGORY, AUTHOR_ID
ORDER BY AUTHOR_ID, CATEGORY DESC