-- 코드를 입력하세요
SELECT AI.ANIMAL_ID, AI.ANIMAL_TYPE, AI.NAME
FROM ANIMAL_INS as AI join ANIMAL_OUTS as AO on AI.ANIMAL_ID = AO.ANIMAL_ID
WHERE AI.SEX_UPON_INTAKE like "Intact%" and (AO.SEX_UPON_OUTCOME like "Neutered%" or AO.SEX_UPON_OUTCOME like  "Spayed%")
order by ANIMAL_ID, ANIMAL_TYPE, NAME