-- 코드를 입력하세요
SELECT YEAR(OS.SALES_DATE) as YEAR, MONTH(OS.SALES_DATE) as MONTH, UI.GENDER, count(DISTINCT UI.USER_ID) as USERS
FROM USER_INFO AS UI INNER JOIN ONLINE_SALE AS OS on UI.USER_ID = OS.USER_ID
where UI.GENDER is not null
group by YEAR, MONTH, GENDER
order by YEAR, MONTH, GENDER