-- 코드를 입력하세요
select FP.PRODUCT_ID, FP.PRODUCT_NAME, PRICE*A.AMOUNT AS TOTAL_SALES
from  FOOD_PRODUCT AS FP INNER JOIN (
        SELECT PRODUCT_ID, SUM(AMOUNT) as AMOUNT
        FROM FOOD_ORDER
        WHERE month(PRODUCE_DATE) = 5 and year(PRODUCE_DATE) = 2022
        group by PRODUCT_ID) AS A ON FP.PRODUCT_ID = A.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID ASC