-- 코드를 입력하세요
SELECT A.FLAVOR
FROM (SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
     FROM FIRST_HALF
     GROUP BY FLAVOR) AS A INNER JOIN 
     (SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
      FROM JULY
      GROUP BY FLAVOR) AS b ON A.FLAVOR = B.FLAVOR
ORDER BY (A.TOTAL_ORDER + B.TOTAL_ORDER) desc
LIMIT 3