-- 코드를 입력하세요
SELECT UGB.WRITER_ID, UGU.NICKNAME, SUM(UGB.PRICE) as TOTAL_SALES
FROM USED_GOODS_BOARD as UGB join USED_GOODS_USER as UGU on UGB.WRITER_ID = UGU.USER_ID
where STATUS = 'DONE'
group by UGB.WRITER_ID
having TOTAL_SALES >= 700000
order by TOTAL_SALES asc