select A.ID, B.FISH_NAME, A.LENGTH
FROM FISH_INFO as A inner JOIn FISH_NAME_INFO as B on A.FISH_TYPE = B.FISH_TYPE
WHERE (A.FISH_TYPE, LENGTH) in (
    SELECT FISH_TYPE, max(LENGTH) as A
    FROM FISH_INFO
    GROUP BY FISH_TYPE
    HAVING A)
    
ORDER BY ID